// biome-ignore-all lint/performance/noBarrelFile: internal sub-barrel of ../index.ts, which stays the only supported import path for these symbols

export { resultTokenStats } from "../result-token-stats";
export type { ResultTokenInput, RunCommitments, TargetNSource } from "../run-commitments";
export {
  ANALYSIS_V1_VERSION,
  ANALYSIS_V2_VERSION,
  CURRENT_ANALYSIS_VERSION,
  createResultToken,
  DEFAULT_PLANNED_DURATION_DAYS,
  DEFAULT_SEQUENTIAL_TARGET_N,
  LEGACY_ANALYSIS_VERSION,
  LEGACY_RUN_COMMITMENTS,
  MAX_PLANNED_DURATION_DAYS,
  PLANNED_DURATION_WEEK_DAYS,
  RunCommitmentsSchema,
  SUPPORTED_ANALYSIS_VERSIONS,
  TargetNSourceSchema,
} from "../run-commitments";
export type {
  FutilityMode,
  PreRegistration,
  PreRegistrationIntent,
  PreRegistrationIssueCode,
  PreRegistrationMetric,
  PreRegistrationRope,
  RopeScale,
  ShipConflictResolution,
  ShipRule,
} from "../run-preregistration";
export {
  FutilityModeSchema,
  PreRegistrationIntentSchema,
  PreRegistrationMetricSchema,
  PreRegistrationRopeSchema,
  PreRegistrationSchema,
  RopeScaleSchema,
  ShipConflictResolutionSchema,
  ShipRuleSchema,
  futilityModes,
  preRegistrationIssueCodes,
  shipConflictResolutions,
} from "../run-preregistration";
export type { PreRegistrationIssue } from "../run-preregistration-resolve";
export {
  preRegistrationToIntent,
  resolvePreRegistration,
} from "../run-preregistration-resolve";
// What the stats engine is handed and what it returns. Grouped because they are
// read together: the analysis knobs frozen on the input (variance config,
// guardrail bounds) are what the result's techniques and guardrail rows report
// back against.
export type {
  ActivationRow,
  CupedCovariateRow,
  CupedCovariateSource,
  DedupeExposureRow,
  DimensionInput,
  GuardrailDecision,
  MetricQueryConfig,
  MetricVarianceConfig,
  PerEntityMetricRow,
  PrePeriodRow,
  StatsInput,
} from "../stats-input-contract";
export {
  ActivationRowSchema,
  CupedCovariateRowSchema,
  CupedCovariateSourceSchema,
  DEFAULT_CUPED,
  DEFAULT_CUPED_COVERAGE_THRESHOLD_PCT,
  DEFAULT_CUPED_LOOKBACK_MS,
  DEFAULT_WINSORIZE,
  DEFAULT_WINSORIZE_PCT,
  DecisionFamilyMemberSchema,
  DedupeExposureRowSchema,
  DimensionInputSchema,
  GuardrailDecisionSchema,
  MetricQueryConfigSchema,
  MetricVarianceConfigSchema,
  PerEntityMetricRowSchema,
  PrePeriodRowSchema,
  StatsInputSchema,
} from "../stats-input-contract";
export type {
  AnalysisResultsEnvelope,
  AnalysisResultsMissingInput,
  ArmResult,
  CupedAttributeSource,
  CupedMethod,
  DimensionClass,
  DimensionResult,
  EstimandDisclosure,
  EstimandLabel,
  FutilityVerdict,
  GuardrailResult,
  HealthMetrics,
  RopeVerdict,
  RopeVerdictUnavailableReason,
  SrmResult,
  StatsEngine,
  StatsOutput,
  StatsResultStatus,
  UncappedEstimate,
  VarianceTechniques,
  WinsorizeCap,
} from "../stats-result-contract";
export {
  AnalysisResultsEnvelopeSchema,
  AnalysisResultsMissingInputSchema,
  ArmResultSchema,
  CupedAttributeSourceSchema,
  CupedMethodSchema,
  cupedAttributeSources,
  cupedMethods,
  DimensionClassSchema,
  DimensionResultSchema,
  dimensionClasses,
  EstimandDisclosureSchema,
  EstimandLabelSchema,
  estimandLabels,
  FutilityVerdictSchema,
  GuardrailResultSchema,
  HealthMetricsSchema,
  RopeVerdictSchema,
  RopeVerdictUnavailableReasonSchema,
  SrmResultSchema,
  StatsOutputSchema,
  StatsResultStatusSchema,
  statsResultStatuses,
  UncappedEstimateSchema,
  VarianceTechniquesSchema,
  WinsorizeCapSchema,
} from "../stats-result-contract";
