/**
 * The canonical control-plane + data-plane endpoint set: the MCP tool list
 * (docs/spec/contracts/mcp-tool-derivation.md) plus the non-MCP routes
 * (openapi discovery + the two data-plane SDK endpoints). Kept explicit so a
 * drift in either direction (an invented or omitted endpoint) fails loudly.
 */
export const CANONICAL_OPERATION_IDS = [
  // Organizations + members
  "organizations_list",
  "organizations_create",
  "organizations_get",
  "organizations_update",
  "organizations_delete",
  "principal_capabilities_get",
  "organization_members_list",
  "organization_members_add",
  "organization_members_update",
  "organization_members_remove",
  // Apps
  "apps_list",
  "apps_create",
  "apps_get",
  "app_attention_rollup_get",
  "apps_update",
  "apps_delete",
  "app_members_list",
  "app_members_add",
  "app_members_update",
  "app_members_remove",
  // Environments
  "environments_list",
  "environments_create",
  "environments_get",
  "environments_update",
  "environments_delete",
  // Approval Requests + Reviews
  "approval_requests_list",
  "approval_requests_get",
  "approval_request_reviews_create",
  // Flags
  "flags_list",
  "principal_flags_list",
  "flags_create",
  "flags_get",
  "flags_update",
  "flags_delete",
  // Variants
  "flag_variants_create",
  "flag_variants_update",
  "flag_variants_delete",
  // Flag Configuration
  "flag_config_get",
  "flag_config_update",
  "flag_targeting_rules_replace",
  "flags_promote",
  "flag_changes_list",
  "flag_changes_export",
  // Segments
  "segments_list",
  "segments_create",
  "segments_get",
  "segments_update",
  "segments_delete",
  // Experiments
  "experiments_list",
  "experiments_create",
  "experiments_get",
  "experiments_update",
  "experiments_start",
  "experiments_delete",
  // Runs
  "runs_list",
  "runs_get",
  "runs_end",
  "runs_conclude",
  "conclusion_promotion_requests_create",
  // Metrics
  "metrics_list",
  "metrics_create",
  "metrics_get",
  "metrics_update",
  "metrics_delete",
  // Event Definitions
  "event_definitions_list",
  "event_definitions_create",
  "event_definitions_get",
  "event_definitions_update",
  "event_definition_versions_create",
  "event_definition_versions_list",
  "event_definition_versions_get",
  // SDK credentials
  "client_key_get",
  "client_key_update",
  "client_key_rotate",
  "api_keys_list",
  "api_keys_create",
  "api_keys_revoke",
  // Convex integration data plane (API Key only, not MCP tools)
  "convex_installations_create",
  "convex_installations_get",
  "convex_installations_delete",
  "convex_secret_rotations_create",
  "convex_snapshot_get",
  "convex_exposures_create",
  // Convex operator door (MCP tools)
  "convex_installations_list",
  "convex_installations_revoke",
  // Cloudflare integration data plane (API Key only, not MCP tools)
  "cloudflare_installations_create",
  "cloudflare_installations_get",
  "cloudflare_installations_delete",
  "cloudflare_exposures_create",
  // Cloudflare operator door (MCP tools)
  "cloudflare_installations_list",
  "cloudflare_installations_revoke",
  // Sentry change tracking: operator door, so these are MCP tools
  "sentry_installations_list",
  "sentry_installations_create",
  "sentry_installations_get",
  "sentry_installations_delete",
  "sentry_secret_rotations_create",
  // Test-eval + analytics + discovery
  "flags_test_eval",
  "experiment_results_get",
  "experiment_results_post",
  "environment_exposure_status_get",
  "environment_exposure_status_delete",
  "holdover_write_outbox_delete",
  "entity_assignment_privacy_export",
  "entity_assignment_privacy_delete",
  "entity_analysis_privacy_export",
  "entity_analysis_privacy_suppress",
  "entity_analysis_privacy_delete",
  "entity_event_privacy_export",
  "entity_event_privacy_suppress",
  "entity_event_privacy_delete",
  "organization_usage_get",
  "openapi_document_get",
  // Privacy
  "current_user_privacy_export",
  "current_user_delete",
  "organization_privacy_export",
  "app_privacy_export",
  "entity_privacy_export",
  "entity_privacy_delete",
  "privacy_requests_get",
  // Data-plane SDK (not MCP tools)
  "sdk_evaluate",
  "sdk_cached_evaluation_telemetry",
  "sdk_peek",
  "sdk_verify",
  "sdk_evaluate_all",
  "sdk_exposures",
  "sdk_track",
  "sdk_activate",
  // OpenFeature Remote Evaluation Protocol (data plane, not MCP tools)
  "ofrep_evaluate",
  "ofrep_evaluate_bulk",
] as const;
