import { z } from "zod";

export const errorCodes = [
  // Validation
  "VALIDATION_ERROR",
  "EVENT_SCHEMA_MISMATCH",
  "ENTITY_TYPE_MISMATCH",
  "ALLOCATION_INVALID",
  "ACTIVATION_TIMESTAMP_INVALID",
  "INVALID_PAGINATION",
  "INVALID_SORT",
  "EXPOSURE_TICKET_INVALID",
  "EXPOSURE_TICKET_EXPIRED",
  "UNSUPPORTED_OBJECT_KEY",

  // Run / Experiment invariants
  "RUN_FROZEN",
  "DECISION_LOCKED",
  "TARGETING_KEY_MISMATCH",
  "RUN_NOT_RUNNING",
  "EXPERIMENT_RUNNING",
  "EXPERIMENT_NO_DRAFT",
  "VARIANT_NOT_AVAILABLE",
  "RESOURCE_NOT_EMPTY",

  // Uniqueness conflicts
  "SLUG_CONFLICT",
  "MEMBERSHIP_CONFLICT",
  "EXPERIMENT_KEY_CONFLICT",
  "SENTRY_INSTALLATION_CONFLICT",
  "EVENT_ID_CONFLICT",
  "EVENT_DEFINITION_UNPUBLISHED",
  "EVENT_DEFINITION_IMMUTABLE",
  "SELECTOR_AMBIGUOUS",

  // Not found
  "EXPERIMENT_NOT_FOUND",
  "RUN_NOT_FOUND",
  "FLAG_NOT_FOUND",
  "VARIANT_NOT_FOUND",
  "METRIC_NOT_FOUND",
  "EVENT_DEFINITION_NOT_FOUND",
  "EVENT_DEFINITION_VERSION_NOT_FOUND",
  "APP_NOT_FOUND",
  "ENVIRONMENT_NOT_FOUND",
  "ORGANIZATION_NOT_FOUND",
  "USER_NOT_FOUND",
  "CREDENTIAL_NOT_FOUND",
  "SEGMENT_NOT_FOUND",
  "PRIVACY_JOB_NOT_FOUND",
  "APPROVAL_REQUEST_NOT_FOUND",
  "CONVEX_INSTALLATION_NOT_FOUND",
  "CLOUDFLARE_INSTALLATION_NOT_FOUND",
  "SENTRY_INSTALLATION_NOT_FOUND",

  // Auth / authz
  "UNAUTHORIZED",
  "CREDENTIAL_REVOKED",
  "INSUFFICIENT_SCOPES",
  "FORBIDDEN",
  "ORIGIN_NOT_ALLOWED",
  "APP_MISMATCH",
  "LAST_OWNER_REQUIRED",
  "LAST_ENVIRONMENT_REQUIRED",
  "PRIVACY_CONFIRMATION_REQUIRED",
  "APPROVAL_REVIEW_FORBIDDEN",

  // Approval Request / Review
  "APPROVAL_REVIEW_REQUIRED",
  "APPROVAL_REQUEST_STALE",
  "DECISION_RESULT_STALE",
  "TARGET_CONFIGURATION_STALE",
  "APPROVAL_REQUEST_RESOLVED",
  "APPROVAL_APPLICATION_FAILED",
  "IDEMPOTENCY_KEY_CONFLICT",

  // Analysis-state signals
  "DECISION_BLOCKED",
  "DECISION_RESULT_UNAVAILABLE",
  "MULTIPLE_VARIANT_CONFLICT",
  "ATTENTION_FANOUT_LIMIT_EXCEEDED",
  "ACTIVATION_NOT_AVAILABLE",

  // System
  "RATE_LIMITED",
  "SERVICE_UNAVAILABLE",
  "PRIVACY_JOB_FAILED",
  "INTERNAL_SERVER_ERROR",
] as const;

export const ErrorCodeSchema = z.enum(errorCodes);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;
