import { z } from "zod";

export const errorCodes = [
  // Validation
  "VALIDATION_ERROR",
  "ALLOCATION_INVALID",
  "ACTIVATION_TIMESTAMP_INVALID",
  "INVALID_PAGINATION",
  "INVALID_SORT",

  // Run / Experiment invariants
  "RUN_FROZEN",
  "DECISION_LOCKED",
  "TARGETING_KEY_MISMATCH",
  "RUN_NOT_RUNNING",
  "EXPERIMENT_RUNNING",
  "EXPERIMENT_NO_DRAFT",
  "VARIANT_NOT_AVAILABLE",
  "RESOURCE_NOT_EMPTY",

  // Uniqueness
  "SLUG_CONFLICT",
  "EXPERIMENT_KEY_CONFLICT",

  // Not found
  "EXPERIMENT_NOT_FOUND",
  "RUN_NOT_FOUND",
  "FLAG_NOT_FOUND",
  "VARIANT_NOT_FOUND",
  "METRIC_NOT_FOUND",
  "APP_NOT_FOUND",
  "ORGANIZATION_NOT_FOUND",
  "USER_NOT_FOUND",
  "CREDENTIAL_NOT_FOUND",
  "SEGMENT_NOT_FOUND",
  "PRIVACY_JOB_NOT_FOUND",
  "APPROVAL_REQUEST_NOT_FOUND",

  // Auth / authz
  "UNAUTHORIZED",
  "CREDENTIAL_REVOKED",
  "INSUFFICIENT_SCOPES",
  "FORBIDDEN",
  "ORIGIN_NOT_ALLOWED",
  "APP_MISMATCH",
  "LAST_OWNER_REQUIRED",
  "LAST_ENVIRONMENT_REQUIRED",
  "PRIVACY_CONFIRMATION_REQUIRED",
  "APPROVAL_REVIEW_FORBIDDEN",

  // Approval Request / Review
  "APPROVAL_REVIEW_REQUIRED",
  "APPROVAL_REQUEST_STALE",
  "APPROVAL_REQUEST_RESOLVED",
  "APPROVAL_APPLICATION_FAILED",
  "IDEMPOTENCY_KEY_CONFLICT",

  // Analysis-state signals
  "MULTIPLE_VARIANT_CONFLICT",
  "ATTENTION_FANOUT_LIMIT_EXCEEDED",

  // System
  "RATE_LIMITED",
  "SERVICE_UNAVAILABLE",
  "PRIVACY_JOB_FAILED",
  "INTERNAL_SERVER_ERROR",
] as const;

export const ErrorCodeSchema = z.enum(errorCodes);
export type ErrorCode = z.infer<typeof ErrorCodeSchema>;
