/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as QuickstartRouteImport } from './routes/quickstart'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsCliDotmdRouteImport } from './routes/docs.cli[.]md'
import { Route as DocsCodeAgentsRouteImport } from './routes/docs.code-agents'
import { Route as DocsCodeAgentsDotmdRouteImport } from './routes/docs.code-agents[.]md'
import { Route as DocsErrorsRouteImport } from './routes/docs.errors'
import { Route as DocsErrorsDotmdRouteImport } from './routes/docs.errors[.]md'
import { Route as DocsFlagsRouteImport } from './routes/docs.flags'
import { Route as DocsFlagsDotmdRouteImport } from './routes/docs.flags[.]md'
import { Route as DocsErrorCodeRouteImport } from './routes/docs.error.$code'
import { Route as DocsSdkTopicRouteImport } from './routes/docs.sdk.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickstartRoute = QuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliDotmdRoute = DocsCliDotmdRouteImport.update({
  id: '/docs/cli.md',
  path: '/docs/cli.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCodeAgentsRoute = DocsCodeAgentsRouteImport.update({
  id: '/docs/code-agents',
  path: '/docs/code-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCodeAgentsDotmdRoute = DocsCodeAgentsDotmdRouteImport.update({
  id: '/docs/code-agents.md',
  path: '/docs/code-agents.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsErrorsRoute = DocsErrorsRouteImport.update({
  id: '/docs/errors',
  path: '/docs/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsErrorsDotmdRoute = DocsErrorsDotmdRouteImport.update({
  id: '/docs/errors.md',
  path: '/docs/errors.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFlagsRoute = DocsFlagsRouteImport.update({
  id: '/docs/flags',
  path: '/docs/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFlagsDotmdRoute = DocsFlagsDotmdRouteImport.update({
  id: '/docs/flags.md',
  path: '/docs/flags.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsErrorCodeRoute = DocsErrorCodeRouteImport.update({
  id: '/docs/error/$code',
  path: '/docs/error/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSdkTopicRoute = DocsSdkTopicRouteImport.update({
  id: '/docs/sdk/$topic',
  path: '/docs/sdk/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quickstart': typeof QuickstartRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/cli.md': typeof DocsCliDotmdRoute
  '/docs/code-agents': typeof DocsCodeAgentsRoute
  '/docs/code-agents.md': typeof DocsCodeAgentsDotmdRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/errors.md': typeof DocsErrorsDotmdRoute
  '/docs/flags': typeof DocsFlagsRoute
  '/docs/flags.md': typeof DocsFlagsDotmdRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/error/$code': typeof DocsErrorCodeRoute
  '/docs/sdk/$topic': typeof DocsSdkTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quickstart': typeof QuickstartRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/cli.md': typeof DocsCliDotmdRoute
  '/docs/code-agents': typeof DocsCodeAgentsRoute
  '/docs/code-agents.md': typeof DocsCodeAgentsDotmdRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/errors.md': typeof DocsErrorsDotmdRoute
  '/docs/flags': typeof DocsFlagsRoute
  '/docs/flags.md': typeof DocsFlagsDotmdRoute
  '/docs': typeof DocsIndexRoute
  '/docs/error/$code': typeof DocsErrorCodeRoute
  '/docs/sdk/$topic': typeof DocsSdkTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quickstart': typeof QuickstartRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/cli.md': typeof DocsCliDotmdRoute
  '/docs/code-agents': typeof DocsCodeAgentsRoute
  '/docs/code-agents.md': typeof DocsCodeAgentsDotmdRoute
  '/docs/errors': typeof DocsErrorsRoute
  '/docs/errors.md': typeof DocsErrorsDotmdRoute
  '/docs/flags': typeof DocsFlagsRoute
  '/docs/flags.md': typeof DocsFlagsDotmdRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/error/$code': typeof DocsErrorCodeRoute
  '/docs/sdk/$topic': typeof DocsSdkTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/llms.txt'
    | '/quickstart'
    | '/.well-known/api-catalog'
    | '/docs/cli'
    | '/docs/cli.md'
    | '/docs/code-agents'
    | '/docs/code-agents.md'
    | '/docs/errors'
    | '/docs/errors.md'
    | '/docs/flags'
    | '/docs/flags.md'
    | '/docs/'
    | '/docs/error/$code'
    | '/docs/sdk/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/llms.txt'
    | '/quickstart'
    | '/.well-known/api-catalog'
    | '/docs/cli'
    | '/docs/cli.md'
    | '/docs/code-agents'
    | '/docs/code-agents.md'
    | '/docs/errors'
    | '/docs/errors.md'
    | '/docs/flags'
    | '/docs/flags.md'
    | '/docs'
    | '/docs/error/$code'
    | '/docs/sdk/$topic'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/llms.txt'
    | '/quickstart'
    | '/.well-known/api-catalog'
    | '/docs/cli'
    | '/docs/cli.md'
    | '/docs/code-agents'
    | '/docs/code-agents.md'
    | '/docs/errors'
    | '/docs/errors.md'
    | '/docs/flags'
    | '/docs/flags.md'
    | '/docs/'
    | '/docs/error/$code'
    | '/docs/sdk/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  QuickstartRoute: typeof QuickstartRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsCliDotmdRoute: typeof DocsCliDotmdRoute
  DocsCodeAgentsRoute: typeof DocsCodeAgentsRoute
  DocsCodeAgentsDotmdRoute: typeof DocsCodeAgentsDotmdRoute
  DocsErrorsRoute: typeof DocsErrorsRoute
  DocsErrorsDotmdRoute: typeof DocsErrorsDotmdRoute
  DocsFlagsRoute: typeof DocsFlagsRoute
  DocsFlagsDotmdRoute: typeof DocsFlagsDotmdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsErrorCodeRoute: typeof DocsErrorCodeRoute
  DocsSdkTopicRoute: typeof DocsSdkTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quickstart': {
      id: '/quickstart'
      path: '/quickstart'
      fullPath: '/quickstart'
      preLoaderRoute: typeof QuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli.md': {
      id: '/docs/cli.md'
      path: '/docs/cli.md'
      fullPath: '/docs/cli.md'
      preLoaderRoute: typeof DocsCliDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/code-agents': {
      id: '/docs/code-agents'
      path: '/docs/code-agents'
      fullPath: '/docs/code-agents'
      preLoaderRoute: typeof DocsCodeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/code-agents.md': {
      id: '/docs/code-agents.md'
      path: '/docs/code-agents.md'
      fullPath: '/docs/code-agents.md'
      preLoaderRoute: typeof DocsCodeAgentsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/errors': {
      id: '/docs/errors'
      path: '/docs/errors'
      fullPath: '/docs/errors'
      preLoaderRoute: typeof DocsErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/errors.md': {
      id: '/docs/errors.md'
      path: '/docs/errors.md'
      fullPath: '/docs/errors.md'
      preLoaderRoute: typeof DocsErrorsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/flags': {
      id: '/docs/flags'
      path: '/docs/flags'
      fullPath: '/docs/flags'
      preLoaderRoute: typeof DocsFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/flags.md': {
      id: '/docs/flags.md'
      path: '/docs/flags.md'
      fullPath: '/docs/flags.md'
      preLoaderRoute: typeof DocsFlagsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/error/$code': {
      id: '/docs/error/$code'
      path: '/docs/error/$code'
      fullPath: '/docs/error/$code'
      preLoaderRoute: typeof DocsErrorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sdk/$topic': {
      id: '/docs/sdk/$topic'
      path: '/docs/sdk/$topic'
      fullPath: '/docs/sdk/$topic'
      preLoaderRoute: typeof DocsSdkTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  QuickstartRoute: QuickstartRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DocsCliRoute: DocsCliRoute,
  DocsCliDotmdRoute: DocsCliDotmdRoute,
  DocsCodeAgentsRoute: DocsCodeAgentsRoute,
  DocsCodeAgentsDotmdRoute: DocsCodeAgentsDotmdRoute,
  DocsErrorsRoute: DocsErrorsRoute,
  DocsErrorsDotmdRoute: DocsErrorsDotmdRoute,
  DocsFlagsRoute: DocsFlagsRoute,
  DocsFlagsDotmdRoute: DocsFlagsDotmdRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsErrorCodeRoute: DocsErrorCodeRoute,
  DocsSdkTopicRoute: DocsSdkTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
