/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as OrgSlugClaimRouteImport } from './routes/$orgSlug.claim'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as OrgSlugAppSlugEnvRouteImport } from './routes/$orgSlug.$appSlug.$env'
import { Route as ClaimConsentAttemptIdRouteImport } from './routes/claim.consent.$attemptId'
import { Route as OrgSlugAppSlugEnvExperimentsRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments'
import { Route as OrgSlugAppSlugEnvFlagsRouteImport } from './routes/$orgSlug.$appSlug.$env.flags'
import { Route as OrgSlugAppSlugEnvMetricsRouteImport } from './routes/$orgSlug.$appSlug.$env.metrics'
import { Route as OrgSlugAppSlugEnvSegmentsRouteImport } from './routes/$orgSlug.$appSlug.$env.segments'
import { Route as OrgSlugAppSlugEnvSettingsRouteImport } from './routes/$orgSlug.$appSlug.$env.settings'
import { Route as OrgSlugAppSlugEnvFlagsFlagIdRouteImport } from './routes/$orgSlug.$appSlug.$env.flags.$flagId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugClaimRoute = OrgSlugClaimRouteImport.update({
  id: '/$orgSlug/claim',
  path: '/$orgSlug/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAppSlugEnvRoute = OrgSlugAppSlugEnvRouteImport.update({
  id: '/$orgSlug/$appSlug/$env',
  path: '/$orgSlug/$appSlug/$env',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimConsentAttemptIdRoute = ClaimConsentAttemptIdRouteImport.update({
  id: '/claim/consent/$attemptId',
  path: '/claim/consent/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAppSlugEnvExperimentsRoute =
  OrgSlugAppSlugEnvExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvFlagsRoute = OrgSlugAppSlugEnvFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => OrgSlugAppSlugEnvRoute,
} as any)
const OrgSlugAppSlugEnvMetricsRoute =
  OrgSlugAppSlugEnvMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvSegmentsRoute =
  OrgSlugAppSlugEnvSegmentsRouteImport.update({
    id: '/segments',
    path: '/segments',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvSettingsRoute =
  OrgSlugAppSlugEnvSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvFlagsFlagIdRoute =
  OrgSlugAppSlugEnvFlagsFlagIdRouteImport.update({
    id: '/$flagId',
    path: '/$flagId',
    getParentRoute: () => OrgSlugAppSlugEnvFlagsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvRouteWithChildren
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsRoute
  '/$orgSlug/$appSlug/$env/flags': typeof OrgSlugAppSlugEnvFlagsRouteWithChildren
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/segments': typeof OrgSlugAppSlugEnvSegmentsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env/flags/$flagId': typeof OrgSlugAppSlugEnvFlagsFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvRouteWithChildren
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsRoute
  '/$orgSlug/$appSlug/$env/flags': typeof OrgSlugAppSlugEnvFlagsRouteWithChildren
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/segments': typeof OrgSlugAppSlugEnvSegmentsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env/flags/$flagId': typeof OrgSlugAppSlugEnvFlagsFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvRouteWithChildren
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsRoute
  '/$orgSlug/$appSlug/$env/flags': typeof OrgSlugAppSlugEnvFlagsRouteWithChildren
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/segments': typeof OrgSlugAppSlugEnvSegmentsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env/flags/$flagId': typeof OrgSlugAppSlugEnvFlagsFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug/'
    | '/$orgSlug/$appSlug/$env'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/flags'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/segments'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env/flags/$flagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug'
    | '/$orgSlug/$appSlug/$env'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/flags'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/segments'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env/flags/$flagId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug/'
    | '/$orgSlug/$appSlug/$env'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/flags'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/segments'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env/flags/$flagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  OrgSlugClaimRoute: typeof OrgSlugClaimRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugAppSlugEnvRoute: typeof OrgSlugAppSlugEnvRouteWithChildren
  ClaimConsentAttemptIdRoute: typeof ClaimConsentAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/claim': {
      id: '/$orgSlug/claim'
      path: '/$orgSlug/claim'
      fullPath: '/$orgSlug/claim'
      preLoaderRoute: typeof OrgSlugClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$appSlug/$env': {
      id: '/$orgSlug/$appSlug/$env'
      path: '/$orgSlug/$appSlug/$env'
      fullPath: '/$orgSlug/$appSlug/$env'
      preLoaderRoute: typeof OrgSlugAppSlugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/consent/$attemptId': {
      id: '/claim/consent/$attemptId'
      path: '/claim/consent/$attemptId'
      fullPath: '/claim/consent/$attemptId'
      preLoaderRoute: typeof ClaimConsentAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$appSlug/$env/experiments': {
      id: '/$orgSlug/$appSlug/$env/experiments'
      path: '/experiments'
      fullPath: '/$orgSlug/$appSlug/$env/experiments'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/flags': {
      id: '/$orgSlug/$appSlug/$env/flags'
      path: '/flags'
      fullPath: '/$orgSlug/$appSlug/$env/flags'
      preLoaderRoute: typeof OrgSlugAppSlugEnvFlagsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/metrics': {
      id: '/$orgSlug/$appSlug/$env/metrics'
      path: '/metrics'
      fullPath: '/$orgSlug/$appSlug/$env/metrics'
      preLoaderRoute: typeof OrgSlugAppSlugEnvMetricsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/segments': {
      id: '/$orgSlug/$appSlug/$env/segments'
      path: '/segments'
      fullPath: '/$orgSlug/$appSlug/$env/segments'
      preLoaderRoute: typeof OrgSlugAppSlugEnvSegmentsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/settings': {
      id: '/$orgSlug/$appSlug/$env/settings'
      path: '/settings'
      fullPath: '/$orgSlug/$appSlug/$env/settings'
      preLoaderRoute: typeof OrgSlugAppSlugEnvSettingsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/flags/$flagId': {
      id: '/$orgSlug/$appSlug/$env/flags/$flagId'
      path: '/$flagId'
      fullPath: '/$orgSlug/$appSlug/$env/flags/$flagId'
      preLoaderRoute: typeof OrgSlugAppSlugEnvFlagsFlagIdRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvFlagsRoute
    }
  }
}

interface OrgSlugAppSlugEnvFlagsRouteChildren {
  OrgSlugAppSlugEnvFlagsFlagIdRoute: typeof OrgSlugAppSlugEnvFlagsFlagIdRoute
}

const OrgSlugAppSlugEnvFlagsRouteChildren: OrgSlugAppSlugEnvFlagsRouteChildren =
  {
    OrgSlugAppSlugEnvFlagsFlagIdRoute: OrgSlugAppSlugEnvFlagsFlagIdRoute,
  }

const OrgSlugAppSlugEnvFlagsRouteWithChildren =
  OrgSlugAppSlugEnvFlagsRoute._addFileChildren(
    OrgSlugAppSlugEnvFlagsRouteChildren,
  )

interface OrgSlugAppSlugEnvRouteChildren {
  OrgSlugAppSlugEnvExperimentsRoute: typeof OrgSlugAppSlugEnvExperimentsRoute
  OrgSlugAppSlugEnvFlagsRoute: typeof OrgSlugAppSlugEnvFlagsRouteWithChildren
  OrgSlugAppSlugEnvMetricsRoute: typeof OrgSlugAppSlugEnvMetricsRoute
  OrgSlugAppSlugEnvSegmentsRoute: typeof OrgSlugAppSlugEnvSegmentsRoute
  OrgSlugAppSlugEnvSettingsRoute: typeof OrgSlugAppSlugEnvSettingsRoute
}

const OrgSlugAppSlugEnvRouteChildren: OrgSlugAppSlugEnvRouteChildren = {
  OrgSlugAppSlugEnvExperimentsRoute: OrgSlugAppSlugEnvExperimentsRoute,
  OrgSlugAppSlugEnvFlagsRoute: OrgSlugAppSlugEnvFlagsRouteWithChildren,
  OrgSlugAppSlugEnvMetricsRoute: OrgSlugAppSlugEnvMetricsRoute,
  OrgSlugAppSlugEnvSegmentsRoute: OrgSlugAppSlugEnvSegmentsRoute,
  OrgSlugAppSlugEnvSettingsRoute: OrgSlugAppSlugEnvSettingsRoute,
}

const OrgSlugAppSlugEnvRouteWithChildren =
  OrgSlugAppSlugEnvRoute._addFileChildren(OrgSlugAppSlugEnvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  OrgSlugClaimRoute: OrgSlugClaimRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugAppSlugEnvRoute: OrgSlugAppSlugEnvRouteWithChildren,
  ClaimConsentAttemptIdRoute: ClaimConsentAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
