/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as KitchenSinkRouteImport } from './routes/kitchen-sink'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as OrgSlugClaimRouteImport } from './routes/$orgSlug.claim'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as OrgSlugAppSlugEnvRouteImport } from './routes/$orgSlug.$appSlug.$env'
import { Route as ClaimConsentAttemptIdRouteImport } from './routes/claim.consent.$attemptId'
import { Route as OrgSlugAppSlugEnvIndexRouteImport } from './routes/$orgSlug.$appSlug.$env.index'
import { Route as OrgSlugAppSlugEnvExperimentsRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments'
import { Route as OrgSlugAppSlugEnvMetricsRouteImport } from './routes/$orgSlug.$appSlug.$env.metrics'
import { Route as OrgSlugAppSlugEnvSettingsRouteImport } from './routes/$orgSlug.$appSlug.$env.settings'
import { Route as OrgSlugAppSlugEnvExperimentsIndexRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.index'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId'
import { Route as OrgSlugAppSlugEnvExperimentsNewRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.new'
import { Route as OrgSlugAppSlugEnvFlagsIndexRouteImport } from './routes/$orgSlug.$appSlug.$env.flags.index'
import { Route as OrgSlugAppSlugEnvFlagsFlagKeyRouteImport } from './routes/$orgSlug.$appSlug.$env.flags.$flagKey'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdIndexRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.index'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdResultsRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.results'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdSetupRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.setup'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdDraftRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments_.$experimentId.draft'
import { Route as OrgSlugAppSlugEnvFlagsFlagKeyPromoteRouteImport } from './routes/$orgSlug.$appSlug.$env.flags.$flagKey_.promote'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.runs.$runId'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.runs.$runId.index'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.runs.$runId.results'
import { Route as OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRouteImport } from './routes/$orgSlug.$appSlug.$env.experiments.$experimentId.runs.$runId.setup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenSinkRoute = KitchenSinkRouteImport.update({
  id: '/kitchen-sink',
  path: '/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugClaimRoute = OrgSlugClaimRouteImport.update({
  id: '/$orgSlug/claim',
  path: '/$orgSlug/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAppSlugEnvRoute = OrgSlugAppSlugEnvRouteImport.update({
  id: '/$orgSlug/$appSlug/$env',
  path: '/$orgSlug/$appSlug/$env',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimConsentAttemptIdRoute = ClaimConsentAttemptIdRouteImport.update({
  id: '/claim/consent/$attemptId',
  path: '/claim/consent/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAppSlugEnvIndexRoute = OrgSlugAppSlugEnvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugAppSlugEnvRoute,
} as any)
const OrgSlugAppSlugEnvExperimentsRoute =
  OrgSlugAppSlugEnvExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvMetricsRoute =
  OrgSlugAppSlugEnvMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvSettingsRoute =
  OrgSlugAppSlugEnvSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsIndexRoute =
  OrgSlugAppSlugEnvExperimentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdRouteImport.update({
    id: '/$experimentId',
    path: '/$experimentId',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsNewRoute =
  OrgSlugAppSlugEnvExperimentsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsRoute,
  } as any)
const OrgSlugAppSlugEnvFlagsIndexRoute =
  OrgSlugAppSlugEnvFlagsIndexRouteImport.update({
    id: '/flags/',
    path: '/flags/',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvFlagsFlagKeyRoute =
  OrgSlugAppSlugEnvFlagsFlagKeyRouteImport.update({
    id: '/flags/$flagKey',
    path: '/flags/$flagKey',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsExperimentIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsExperimentIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsExperimentIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdDraftRouteImport.update({
    id: '/experiments_/$experimentId/draft',
    path: '/experiments/$experimentId/draft',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute =
  OrgSlugAppSlugEnvFlagsFlagKeyPromoteRouteImport.update({
    id: '/flags/$flagKey_/promote',
    path: '/flags/$flagKey/promote',
    getParentRoute: () => OrgSlugAppSlugEnvRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => OrgSlugAppSlugEnvExperimentsExperimentIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () =>
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute,
  } as any)
const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute =
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () =>
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvRouteWithChildren
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsRouteWithChildren
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env/': typeof OrgSlugAppSlugEnvIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRouteWithChildren
  '/$orgSlug/$appSlug/$env/experiments/new': typeof OrgSlugAppSlugEnvExperimentsNewRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey': typeof OrgSlugAppSlugEnvFlagsFlagKeyRoute
  '/$orgSlug/$appSlug/$env/experiments/': typeof OrgSlugAppSlugEnvExperimentsIndexRoute
  '/$orgSlug/$appSlug/$env/flags/': typeof OrgSlugAppSlugEnvFlagsIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/draft': typeof OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey/promote': typeof OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/': typeof OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteWithChildren
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/new': typeof OrgSlugAppSlugEnvExperimentsNewRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey': typeof OrgSlugAppSlugEnvFlagsFlagKeyRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsIndexRoute
  '/$orgSlug/$appSlug/$env/flags': typeof OrgSlugAppSlugEnvFlagsIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/draft': typeof OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey/promote': typeof OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/kitchen-sink': typeof KitchenSinkRoute
  '/$orgSlug/claim': typeof OrgSlugClaimRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/$appSlug/$env': typeof OrgSlugAppSlugEnvRouteWithChildren
  '/claim/consent/$attemptId': typeof ClaimConsentAttemptIdRoute
  '/$orgSlug/$appSlug/$env/experiments': typeof OrgSlugAppSlugEnvExperimentsRouteWithChildren
  '/$orgSlug/$appSlug/$env/metrics': typeof OrgSlugAppSlugEnvMetricsRoute
  '/$orgSlug/$appSlug/$env/settings': typeof OrgSlugAppSlugEnvSettingsRoute
  '/$orgSlug/$appSlug/$env/': typeof OrgSlugAppSlugEnvIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRouteWithChildren
  '/$orgSlug/$appSlug/$env/experiments/new': typeof OrgSlugAppSlugEnvExperimentsNewRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey': typeof OrgSlugAppSlugEnvFlagsFlagKeyRoute
  '/$orgSlug/$appSlug/$env/experiments/': typeof OrgSlugAppSlugEnvExperimentsIndexRoute
  '/$orgSlug/$appSlug/$env/flags/': typeof OrgSlugAppSlugEnvFlagsIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments_/$experimentId/draft': typeof OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute
  '/$orgSlug/$appSlug/$env/flags/$flagKey_/promote': typeof OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/': typeof OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteWithChildren
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute
  '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/': typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug/'
    | '/$orgSlug/$appSlug/$env'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId'
    | '/$orgSlug/$appSlug/$env/experiments/new'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey'
    | '/$orgSlug/$appSlug/$env/experiments/'
    | '/$orgSlug/$appSlug/$env/flags/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/draft'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey/promote'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env'
    | '/$orgSlug/$appSlug/$env/experiments/new'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/flags'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/draft'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey/promote'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/kitchen-sink'
    | '/$orgSlug/claim'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/$orgSlug/'
    | '/$orgSlug/$appSlug/$env'
    | '/claim/consent/$attemptId'
    | '/$orgSlug/$appSlug/$env/experiments'
    | '/$orgSlug/$appSlug/$env/metrics'
    | '/$orgSlug/$appSlug/$env/settings'
    | '/$orgSlug/$appSlug/$env/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId'
    | '/$orgSlug/$appSlug/$env/experiments/new'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey'
    | '/$orgSlug/$appSlug/$env/experiments/'
    | '/$orgSlug/$appSlug/$env/flags/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup'
    | '/$orgSlug/$appSlug/$env/experiments_/$experimentId/draft'
    | '/$orgSlug/$appSlug/$env/flags/$flagKey_/promote'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup'
    | '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  KitchenSinkRoute: typeof KitchenSinkRoute
  OrgSlugClaimRoute: typeof OrgSlugClaimRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugAppSlugEnvRoute: typeof OrgSlugAppSlugEnvRouteWithChildren
  ClaimConsentAttemptIdRoute: typeof ClaimConsentAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-sink': {
      id: '/kitchen-sink'
      path: '/kitchen-sink'
      fullPath: '/kitchen-sink'
      preLoaderRoute: typeof KitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/claim': {
      id: '/$orgSlug/claim'
      path: '/$orgSlug/claim'
      fullPath: '/$orgSlug/claim'
      preLoaderRoute: typeof OrgSlugClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$appSlug/$env': {
      id: '/$orgSlug/$appSlug/$env'
      path: '/$orgSlug/$appSlug/$env'
      fullPath: '/$orgSlug/$appSlug/$env'
      preLoaderRoute: typeof OrgSlugAppSlugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/consent/$attemptId': {
      id: '/claim/consent/$attemptId'
      path: '/claim/consent/$attemptId'
      fullPath: '/claim/consent/$attemptId'
      preLoaderRoute: typeof ClaimConsentAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/$appSlug/$env/': {
      id: '/$orgSlug/$appSlug/$env/'
      path: '/'
      fullPath: '/$orgSlug/$appSlug/$env/'
      preLoaderRoute: typeof OrgSlugAppSlugEnvIndexRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/experiments': {
      id: '/$orgSlug/$appSlug/$env/experiments'
      path: '/experiments'
      fullPath: '/$orgSlug/$appSlug/$env/experiments'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/metrics': {
      id: '/$orgSlug/$appSlug/$env/metrics'
      path: '/metrics'
      fullPath: '/$orgSlug/$appSlug/$env/metrics'
      preLoaderRoute: typeof OrgSlugAppSlugEnvMetricsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/settings': {
      id: '/$orgSlug/$appSlug/$env/settings'
      path: '/settings'
      fullPath: '/$orgSlug/$appSlug/$env/settings'
      preLoaderRoute: typeof OrgSlugAppSlugEnvSettingsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/': {
      id: '/$orgSlug/$appSlug/$env/experiments/'
      path: '/'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsIndexRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId'
      path: '/$experimentId'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/new': {
      id: '/$orgSlug/$appSlug/$env/experiments/new'
      path: '/new'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/new'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsNewRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsRoute
    }
    '/$orgSlug/$appSlug/$env/flags/': {
      id: '/$orgSlug/$appSlug/$env/flags/'
      path: '/flags'
      fullPath: '/$orgSlug/$appSlug/$env/flags/'
      preLoaderRoute: typeof OrgSlugAppSlugEnvFlagsIndexRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/flags/$flagKey': {
      id: '/$orgSlug/$appSlug/$env/flags/$flagKey'
      path: '/flags/$flagKey'
      fullPath: '/$orgSlug/$appSlug/$env/flags/$flagKey'
      preLoaderRoute: typeof OrgSlugAppSlugEnvFlagsFlagKeyRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/'
      path: '/'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdIndexRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/results': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/results'
      path: '/results'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/results'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdResultsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup'
      path: '/setup'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/setup'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdSetupRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments_/$experimentId/draft': {
      id: '/$orgSlug/$appSlug/$env/experiments_/$experimentId/draft'
      path: '/experiments/$experimentId/draft'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/draft'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdDraftRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/flags/$flagKey_/promote': {
      id: '/$orgSlug/$appSlug/$env/flags/$flagKey_/promote'
      path: '/flags/$flagKey/promote'
      fullPath: '/$orgSlug/$appSlug/$env/flags/$flagKey/promote'
      preLoaderRoute: typeof OrgSlugAppSlugEnvFlagsFlagKeyPromoteRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/'
      path: '/'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results'
      path: '/results'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/results'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute
    }
    '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup': {
      id: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup'
      path: '/setup'
      fullPath: '/$orgSlug/$appSlug/$env/experiments/$experimentId/runs/$runId/setup'
      preLoaderRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRouteImport
      parentRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute
    }
  }
}

interface OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteChildren {
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute
}

const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteChildren: OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteChildren =
  {
    OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdResultsRoute,
    OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdSetupRoute,
    OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdIndexRoute,
  }

const OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteWithChildren =
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute._addFileChildren(
    OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteChildren,
  )

interface OrgSlugAppSlugEnvExperimentsExperimentIdRouteChildren {
  OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteWithChildren
}

const OrgSlugAppSlugEnvExperimentsExperimentIdRouteChildren: OrgSlugAppSlugEnvExperimentsExperimentIdRouteChildren =
  {
    OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdResultsRoute,
    OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdSetupRoute,
    OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdIndexRoute,
    OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdRunsRunIdRouteWithChildren,
  }

const OrgSlugAppSlugEnvExperimentsExperimentIdRouteWithChildren =
  OrgSlugAppSlugEnvExperimentsExperimentIdRoute._addFileChildren(
    OrgSlugAppSlugEnvExperimentsExperimentIdRouteChildren,
  )

interface OrgSlugAppSlugEnvExperimentsRouteChildren {
  OrgSlugAppSlugEnvExperimentsExperimentIdRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdRouteWithChildren
  OrgSlugAppSlugEnvExperimentsNewRoute: typeof OrgSlugAppSlugEnvExperimentsNewRoute
  OrgSlugAppSlugEnvExperimentsIndexRoute: typeof OrgSlugAppSlugEnvExperimentsIndexRoute
}

const OrgSlugAppSlugEnvExperimentsRouteChildren: OrgSlugAppSlugEnvExperimentsRouteChildren =
  {
    OrgSlugAppSlugEnvExperimentsExperimentIdRoute:
      OrgSlugAppSlugEnvExperimentsExperimentIdRouteWithChildren,
    OrgSlugAppSlugEnvExperimentsNewRoute: OrgSlugAppSlugEnvExperimentsNewRoute,
    OrgSlugAppSlugEnvExperimentsIndexRoute:
      OrgSlugAppSlugEnvExperimentsIndexRoute,
  }

const OrgSlugAppSlugEnvExperimentsRouteWithChildren =
  OrgSlugAppSlugEnvExperimentsRoute._addFileChildren(
    OrgSlugAppSlugEnvExperimentsRouteChildren,
  )

interface OrgSlugAppSlugEnvRouteChildren {
  OrgSlugAppSlugEnvExperimentsRoute: typeof OrgSlugAppSlugEnvExperimentsRouteWithChildren
  OrgSlugAppSlugEnvMetricsRoute: typeof OrgSlugAppSlugEnvMetricsRoute
  OrgSlugAppSlugEnvSettingsRoute: typeof OrgSlugAppSlugEnvSettingsRoute
  OrgSlugAppSlugEnvIndexRoute: typeof OrgSlugAppSlugEnvIndexRoute
  OrgSlugAppSlugEnvFlagsFlagKeyRoute: typeof OrgSlugAppSlugEnvFlagsFlagKeyRoute
  OrgSlugAppSlugEnvFlagsIndexRoute: typeof OrgSlugAppSlugEnvFlagsIndexRoute
  OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute: typeof OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute
  OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute: typeof OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute
}

const OrgSlugAppSlugEnvRouteChildren: OrgSlugAppSlugEnvRouteChildren = {
  OrgSlugAppSlugEnvExperimentsRoute:
    OrgSlugAppSlugEnvExperimentsRouteWithChildren,
  OrgSlugAppSlugEnvMetricsRoute: OrgSlugAppSlugEnvMetricsRoute,
  OrgSlugAppSlugEnvSettingsRoute: OrgSlugAppSlugEnvSettingsRoute,
  OrgSlugAppSlugEnvIndexRoute: OrgSlugAppSlugEnvIndexRoute,
  OrgSlugAppSlugEnvFlagsFlagKeyRoute: OrgSlugAppSlugEnvFlagsFlagKeyRoute,
  OrgSlugAppSlugEnvFlagsIndexRoute: OrgSlugAppSlugEnvFlagsIndexRoute,
  OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute:
    OrgSlugAppSlugEnvExperimentsExperimentIdDraftRoute,
  OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute:
    OrgSlugAppSlugEnvFlagsFlagKeyPromoteRoute,
}

const OrgSlugAppSlugEnvRouteWithChildren =
  OrgSlugAppSlugEnvRoute._addFileChildren(OrgSlugAppSlugEnvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  KitchenSinkRoute: KitchenSinkRoute,
  OrgSlugClaimRoute: OrgSlugClaimRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugAppSlugEnvRoute: OrgSlugAppSlugEnvRouteWithChildren,
  ClaimConsentAttemptIdRoute: ClaimConsentAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
