export const APPROVAL_WRITE_ERRORS = [
  "APPROVAL_REVIEW_REQUIRED",
  "APPROVAL_REVIEW_FORBIDDEN",
  "APPROVAL_REQUEST_STALE",
  "APPROVAL_REQUEST_RESOLVED",
  "APPROVAL_APPLICATION_FAILED",
  "IDEMPOTENCY_KEY_CONFLICT",
] as const;
