import { z } from "@hono/zod-openapi";
import { type ApiRouteContract, defineApiRoute } from "../openapi-route";
import {
  CreateFlagRequestSchema,
  CreateVariantRequestSchema,
  FlagListReadResponseSchema,
  FlagMutationResponseSchema,
  FlagReadResponseSchema,
  FlagResponseSchema,
  PatchFlagRequestSchema,
  PatchVariantRequestSchema,
  PrincipalFlagListReadResponseSchema,
} from "../resource-envelopes-flag";
import {
  AppParams,
  EnvFlagParams,
  FlagConfigMutationResponseSchema,
  FlagConfigResponseSchema,
  FlagGetQuerySchema,
  FlagListQuerySchema,
  FlagParams,
  FlagVariantParams,
  PatchFlagConfigRequestSchema,
  PromoteParams,
  PrincipalFlagListQuerySchema,
  PromoteRequestSchema,
  PromoteResponseSchema,
  ReplaceTargetingRulesRequestSchema,
} from "./route-shapes";

/**
 * Flag definition (App-level catalog), Variant sub-resource, per-Environment Flag
 * Configuration, Promotion, and Segment routes. Control Plane API Worker.
 * Endpoint canon: docs/spec/control-plane/endpoints-flag-segment.md.
 */

const OWNER = "control-plane-api" as const;
const AUTH = "control-plane-token" as const;
const RATE = "control-plane-actor" as const;

const DeletedResponse = z.object({ deleted: z.literal(true) });
const APPROVAL_WRITE_ERRORS = [
  "APPROVAL_REVIEW_REQUIRED",
  "APPROVAL_REVIEW_FORBIDDEN",
  "APPROVAL_REQUEST_STALE",
  "APPROVAL_REQUEST_RESOLVED",
  "APPROVAL_APPLICATION_FAILED",
  "IDEMPOTENCY_KEY_CONFLICT",
] as const;

export const flagRoutes = [
  defineApiRoute({
    operationId: "flags_list",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/flags",
    summary: "List Flag definitions in an App (bounded; reports its own truncation).",
    request: { params: AppParams, query: FlagListQuerySchema },
    response: FlagListReadResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "ENVIRONMENT_NOT_FOUND", "FORBIDDEN", "INTERNAL_SERVER_ERROR"],
  }),
  defineApiRoute({
    operationId: "flags_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/flags",
    summary: "Create a Flag definition (key, schema, Variant catalog).",
    request: { params: AppParams, body: CreateFlagRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR", "IDEMPOTENCY_KEY_CONFLICT"],
  }),
  defineApiRoute({
    operationId: "flags_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/flags/:flagId",
    summary: "Get a Flag definition by canonical ID or key.",
    request: { params: FlagParams, query: FlagGetQuerySchema },
    response: FlagReadResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "ENVIRONMENT_NOT_FOUND", "FORBIDDEN", "INTERNAL_SERVER_ERROR"],
  }),
  defineApiRoute({
    operationId: "flags_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/flags/:flagId",
    summary: "Update a Flag definition's name/description/schema.",
    request: { params: FlagParams, body: PatchFlagRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flags_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/flags/:flagId",
    summary: "Delete a Flag (blocked if referenced by a running Experiment).",
    request: { params: FlagParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "FORBIDDEN",
      "EXPERIMENT_RUNNING",
      "RESOURCE_NOT_EMPTY",
      ...APPROVAL_WRITE_ERRORS,
    ],
  }),
  defineApiRoute({
    operationId: "flag_variants_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/flags/:flagId/variants",
    summary: "Add a Variant to the App-level catalog.",
    request: { params: FlagParams, body: CreateVariantRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN", ...APPROVAL_WRITE_ERRORS, "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flag_variants_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/flags/:flagId/variants/:variantName",
    summary: "Update a catalog Variant (value is Run-frozen).",
    request: { params: FlagVariantParams, body: PatchVariantRequestSchema },
    response: FlagMutationResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_FOUND",
      "FORBIDDEN",
      "RUN_FROZEN",
      ...APPROVAL_WRITE_ERRORS,
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flag_variants_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/flags/:flagId/variants/:variantName",
    summary:
      "Remove a catalog Variant (blocked if available, referenced by a Targeting Rule, or in a running Run).",
    request: { params: FlagVariantParams },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_FOUND",
      "FORBIDDEN",
      "EXPERIMENT_RUNNING",
      "RESOURCE_NOT_EMPTY",
      ...APPROVAL_WRITE_ERRORS,
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flag_config_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/config",
    summary: "Get a Flag's per-Environment Configuration.",
    request: { params: EnvFlagParams },
    response: FlagConfigResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "flag_config_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/config",
    summary: "Update enabled state / available Variants (Policy-gated change types).",
    request: { params: EnvFlagParams, body: PatchFlagConfigRequestSchema },
    response: FlagConfigMutationResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "SEGMENT_NOT_FOUND",
      "FORBIDDEN",
      // A live Run owns availability and the baseline rollout in its Environment
      // and refuses both; `enabled` is exempt so the kill switch always works.
      "RUN_FROZEN",
      ...APPROVAL_WRITE_ERRORS,
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flag_targeting_rules_replace",
    owner: OWNER,
    method: "PUT",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/targeting-rules",
    summary: "Full-replace this Environment's ordered Targeting Rule list.",
    request: { params: EnvFlagParams, body: ReplaceTargetingRulesRequestSchema },
    response: FlagConfigMutationResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "SEGMENT_NOT_FOUND",
      "FORBIDDEN",
      // A live Run owns this Environment's Targeting and refuses the replace.
      "RUN_FROZEN",
      ...APPROVAL_WRITE_ERRORS,
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flags_promote",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/envs/:targetEnvironmentId/flags/:flagId/promote",
    summary: "Promote selected Flag Configuration field-groups between Environments.",
    request: { params: PromoteParams, body: PromoteRequestSchema },
    response: PromoteResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "required",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "SEGMENT_NOT_FOUND",
      "FORBIDDEN",
      // A live Run in the TARGET Environment owns the availability, baseline
      // rollout, and Targeting a Promotion would overwrite there.
      "RUN_FROZEN",
      ...APPROVAL_WRITE_ERRORS,
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "principal_flags_list",
    owner: OWNER,
    method: "GET",
    path: "/flags",
    summary:
      "List every readable Flag across the principal's Apps, ordered by App then Flag key (bounded; reports its own truncation).",
    request: { query: PrincipalFlagListQuerySchema },
    response: PrincipalFlagListReadResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FORBIDDEN"],
  }),
] as const satisfies readonly ApiRouteContract[];
