import { z } from "@hono/zod-openapi";
import {
  CreateFlagRequestSchema,
  CreateVariantRequestSchema,
  FlagResponseSchema,
  PatchFlagRequestSchema,
  PatchVariantRequestSchema,
} from "../resource-envelopes-flag";
import { SegmentSchema } from "../leaf-schemas-flag";
import { type ApiRouteContract, defineApiRoute } from "../openapi-route";
import {
  AppParams,
  CreateSegmentRequestSchema,
  EnvFlagParams,
  FlagConfigResponseSchema,
  FlagParams,
  FlagVariantParams,
  PatchFlagConfigRequestSchema,
  PatchSegmentRequestSchema,
  PromoteParams,
  PromoteRequestSchema,
  PromoteResponseSchema,
  ReplaceTargetingRulesRequestSchema,
  SegmentParams,
} from "./route-shapes";

/**
 * Flag definition (App-level catalog), Variant sub-resource, per-Environment Flag
 * Configuration, Promotion, and Segment routes. Control Plane API Worker.
 * Endpoint canon: docs/spec/control-plane/endpoints-flag-segment.md.
 */

const OWNER = "control-plane-api" as const;
const AUTH = "control-plane-token" as const;
const RATE = "control-plane-actor" as const;

const FlagListResponse = z.object({ items: z.array(FlagResponseSchema) });
const SegmentListResponse = z.object({ items: z.array(SegmentSchema) });
const DeletedResponse = z.object({ deleted: z.literal(true) });

export const flagRoutes = [
  defineApiRoute({
    operationId: "flags_list",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/flags",
    summary: "List Flag definitions in an App.",
    request: { params: AppParams },
    response: FlagListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "flags_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/flags",
    summary: "Create a Flag definition (key, schema, Variant catalog).",
    request: { params: AppParams, body: CreateFlagRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flags_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/flags/:flagId",
    summary: "Get a Flag definition.",
    request: { params: FlagParams },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "flags_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/flags/:flagId",
    summary: "Update a Flag definition's name/description/schema.",
    request: { params: FlagParams, body: PatchFlagRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flags_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/flags/:flagId",
    summary: "Delete a Flag (blocked if referenced by a running Experiment).",
    request: { params: FlagParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN", "EXPERIMENT_RUNNING", "RESOURCE_NOT_EMPTY"],
  }),
  defineApiRoute({
    operationId: "flag_variants_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/flags/:flagId/variants",
    summary: "Add a Variant to the App-level catalog.",
    request: { params: FlagParams, body: CreateVariantRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "optional",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flag_variants_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/flags/:flagId/variants/:variantName",
    summary: "Update a catalog Variant (value is Run-frozen).",
    request: { params: FlagVariantParams, body: PatchVariantRequestSchema },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "VARIANT_NOT_FOUND", "FORBIDDEN", "RUN_FROZEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "flag_variants_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/flags/:flagId/variants/:variantName",
    summary: "Remove a catalog Variant (blocked if available or in a running Run).",
    request: { params: FlagVariantParams },
    response: FlagResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_FOUND",
      "FORBIDDEN",
      "EXPERIMENT_RUNNING",
      "RESOURCE_NOT_EMPTY",
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flag_config_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/config",
    summary: "Get a Flag's per-Environment Configuration.",
    request: { params: EnvFlagParams },
    response: FlagConfigResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["FLAG_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "flag_config_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/config",
    summary: "Update enabled state / available Variants (Policy-gated change types).",
    request: { params: EnvFlagParams, body: PatchFlagConfigRequestSchema },
    response: FlagConfigResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "FORBIDDEN",
      "CONFIRMATION_REQUIRED",
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flag_targeting_rules_replace",
    owner: OWNER,
    method: "PUT",
    path: "/apps/:appId/envs/:environmentId/flags/:flagId/targeting-rules",
    summary: "Full-replace this Environment's ordered Targeting Rule list.",
    request: { params: EnvFlagParams, body: ReplaceTargetingRulesRequestSchema },
    response: FlagConfigResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "FORBIDDEN",
      "CONFIRMATION_REQUIRED",
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "flags_promote",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/envs/:targetEnvironmentId/flags/:flagId/promote",
    summary: "Promote selected Flag Configuration field-groups between Environments.",
    request: { params: PromoteParams, body: PromoteRequestSchema },
    response: PromoteResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "FLAG_NOT_FOUND",
      "VARIANT_NOT_AVAILABLE",
      "FORBIDDEN",
      "CONFIRMATION_REQUIRED",
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "segments_list",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/segments",
    summary: "List Segments in an App.",
    request: { params: AppParams },
    response: SegmentListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "segments_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/segments",
    summary: "Create a Segment.",
    request: { params: AppParams, body: CreateSegmentRequestSchema },
    response: SegmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "optional",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "segments_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/segments/:segmentId",
    summary: "Get a Segment.",
    request: { params: SegmentParams },
    response: SegmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["SEGMENT_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "segments_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/segments/:segmentId",
    summary: "Update a Segment.",
    request: { params: SegmentParams, body: PatchSegmentRequestSchema },
    response: SegmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["SEGMENT_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "segments_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/segments/:segmentId",
    summary: "Delete a Segment (blocked if referenced by a running Experiment).",
    request: { params: SegmentParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["SEGMENT_NOT_FOUND", "FORBIDDEN", "EXPERIMENT_RUNNING"],
  }),
] as const satisfies readonly ApiRouteContract[];
