import { z } from "@hono/zod-openapi";
import {
  CreateAppRequestSchema,
  CreateAppResponseSchema,
  OrganizationResponseSchema,
  PatchAppRequestSchema,
  PatchOrganizationRequestSchema,
} from "../resource-envelopes-account";
import { AppSchema, EnvironmentSchema, UserSchema } from "../leaf-schemas-runtime";
import { type ApiRouteContract, defineApiRoute } from "../openapi-route";
import {
  AddMemberRequestSchema,
  AppParams,
  CreateEnvironmentRequestSchema,
  EnvParams,
  OrgAppsParams,
  OrgMemberParams,
  OrgParams,
  PatchEnvironmentRequestSchema,
  UpdateMemberRequestSchema,
} from "./route-shapes";

/**
 * Organization, member, App, and Environment management routes — all on the
 * Control Plane API Worker, control-plane token + control-plane-actor rate class.
 * Endpoint canon: docs/spec/control-plane/endpoints-org-app.md.
 */

const OWNER = "control-plane-api" as const;
const AUTH = "control-plane-token" as const;
const RATE = "control-plane-actor" as const;

const OrgListResponse = z.object({ items: z.array(OrganizationResponseSchema) });
const AppListResponse = z.object({ items: z.array(AppSchema) });
const EnvListResponse = z.object({ items: z.array(EnvironmentSchema) });
const MemberListResponse = z.object({ items: z.array(UserSchema) });
const MemberResponse = UserSchema;
const DeletedResponse = z.object({ deleted: z.literal(true) });

export const accountRoutes = [
  defineApiRoute({
    operationId: "organizations_list",
    owner: OWNER,
    method: "GET",
    path: "/orgs",
    summary: "List organizations the token can reach (agent cold-start entry).",
    response: OrgListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [],
  }),
  defineApiRoute({
    operationId: "organizations_get",
    owner: OWNER,
    method: "GET",
    path: "/orgs/:orgId",
    summary: "Get one organization.",
    request: { params: OrgParams },
    response: OrganizationResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "organizations_update",
    owner: OWNER,
    method: "PATCH",
    path: "/orgs/:orgId",
    summary: "Rename an organization or change its plan.",
    request: { params: OrgParams, body: PatchOrganizationRequestSchema },
    response: OrganizationResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "organizations_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/orgs/:orgId",
    summary: "Delete an organization (requires a prior dry-run confirmation token).",
    request: { params: OrgParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN", "PRIVACY_CONFIRMATION_REQUIRED"],
  }),
  defineApiRoute({
    operationId: "organization_members_list",
    owner: OWNER,
    method: "GET",
    path: "/orgs/:orgId/members",
    summary: "List organization members.",
    request: { params: OrgParams },
    response: MemberListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "USER_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "organization_members_add",
    owner: OWNER,
    method: "POST",
    path: "/orgs/:orgId/members",
    summary: "Add a member to an organization.",
    request: { params: OrgParams, body: AddMemberRequestSchema },
    response: MemberResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN", "USER_NOT_FOUND", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "organization_members_update",
    owner: OWNER,
    method: "PATCH",
    path: "/orgs/:orgId/members/:userId",
    summary: "Change a member's role.",
    request: { params: OrgMemberParams, body: UpdateMemberRequestSchema },
    response: MemberResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "ORGANIZATION_NOT_FOUND",
      "USER_NOT_FOUND",
      "FORBIDDEN",
      "LAST_OWNER_REQUIRED",
      "VALIDATION_ERROR",
    ],
  }),
  defineApiRoute({
    operationId: "organization_members_remove",
    owner: OWNER,
    method: "DELETE",
    path: "/orgs/:orgId/members/:userId",
    summary: "Remove a member (rejected if removing the last owner).",
    request: { params: OrgMemberParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "USER_NOT_FOUND", "FORBIDDEN", "LAST_OWNER_REQUIRED"],
  }),
  defineApiRoute({
    operationId: "apps_list",
    owner: OWNER,
    method: "GET",
    path: "/orgs/:orgId/apps",
    summary: "List the Apps in an organization.",
    request: { params: OrgAppsParams },
    response: AppListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "apps_create",
    owner: OWNER,
    method: "POST",
    path: "/orgs/:orgId/apps",
    summary: "Create an App (provisions dev + prod Environments and Client Keys).",
    request: { params: OrgAppsParams, body: CreateAppRequestSchema },
    response: CreateAppResponseSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "optional",
    errors: ["ORGANIZATION_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "apps_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId",
    summary: "Get one App.",
    request: { params: AppParams },
    response: AppSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "apps_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId",
    summary: "Rename an App.",
    request: { params: AppParams, body: PatchAppRequestSchema },
    response: AppSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "apps_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId",
    summary: "Delete an App (blocked while any Experiment is running).",
    request: { params: AppParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "EXPERIMENT_RUNNING", "RESOURCE_NOT_EMPTY"],
  }),
  defineApiRoute({
    operationId: "environments_list",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/envs",
    summary: "List an App's Environments.",
    request: { params: AppParams },
    response: EnvListResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "environments_create",
    owner: OWNER,
    method: "POST",
    path: "/apps/:appId/envs",
    summary: "Create an Environment (auto-provisions its Client Key).",
    request: { params: AppParams, body: CreateEnvironmentRequestSchema },
    response: EnvironmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "environments_get",
    owner: OWNER,
    method: "GET",
    path: "/apps/:appId/envs/:environmentId",
    summary: "Get one Environment (includes its inline Policy).",
    request: { params: EnvParams },
    response: EnvironmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN"],
  }),
  defineApiRoute({
    operationId: "environments_update",
    owner: OWNER,
    method: "PATCH",
    path: "/apps/:appId/envs/:environmentId",
    summary: "Rename an Environment or edit its Policy.",
    request: { params: EnvParams, body: PatchEnvironmentRequestSchema },
    response: EnvironmentSchema,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: ["APP_NOT_FOUND", "FORBIDDEN", "VALIDATION_ERROR"],
  }),
  defineApiRoute({
    operationId: "environments_delete",
    owner: OWNER,
    method: "DELETE",
    path: "/apps/:appId/envs/:environmentId",
    summary: "Delete an Environment (blocked if running or last Environment).",
    request: { params: EnvParams },
    response: DeletedResponse,
    auth: AUTH,
    rateLimit: RATE,
    idempotency: "none",
    errors: [
      "APP_NOT_FOUND",
      "FORBIDDEN",
      "EXPERIMENT_RUNNING",
      "LAST_ENVIRONMENT_REQUIRED",
      "RESOURCE_NOT_EMPTY",
    ],
  }),
] as const satisfies readonly ApiRouteContract[];
